### ISSUE TITLE
Library endpoints fail when no plex is connected or channels exist

### ISSUE THREAD

**Issue by markdavella** [chrisbenincasa/tunarr#156] opened 2024-03-08 01:55 UTC
If you click either of these links as a new account
<img width="1624" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/80e351b5-ca12-4051-b705-c0b56b2721b2">

you get this:
<img width="1633" alt="image" src="https://github.com/chrisbenincasa/tunarr/assets/6005331/99f5cbef-e96c-4551-94ac-c2ffe3daa351">

**Comment by chrisbenincasa** [comment] 2024-03-08 16:32
Based on the error in the logs I think this is a dupe of #158 (the server crashed and we can't connect)

**Closed by chrisbenincasa** 2024-03-08 16:32 UTC
Labels: bug, frontend
