### ISSUE TITLE
Cannot add media due to Plex library setup

### ISSUE THREAD

**Issue by YaBoiDan** [chrisbenincasa/tunarr#721] opened 2024-08-26 22:42 UTC
### What happened?

I have two Plex libraries, the first is shown (I assume as it's alphabetically first) contains just a music library and a second for Video, TV and Other Video. In some cases, I cannot select the second as this error is presented and the 'This is fine' image is shown. I was able to once get to this server, create a filler programme, but when I now add media, it attempts to go to this server and immediately shows the error, not allowing me to progress. 

### Version

0.7.0

### What browser did you experience the the problem on?

Microsoft Edge (128.0.0.0)

### What operating system are you using?

macOS (10.15.7)

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'guid')
    at CE (http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:416:114329)
    at http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:416:114479
    at Array.reduce (<anonymous>)
    at http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:416:114457
    at http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:315:10600
    at N4e.produce (http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:315:10751)
    at http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:315:10585
    at r (http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:311:42055)
    at r.setState (http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:315:12622)
    at i.setState (http://192.168.xxx.xxx:8001/web/assets/index-CR57dIMz.js:315:3562)
```

**Comment by chrisbenincasa** [comment] 2024-08-26 23:53
Thanks for the report. I'll have a look!

**Comment by chrisbenincasa** [comment] 2024-08-27 00:46
Just so I'm clear -- there are 2 Plex servers? or these are 2 libraries within the same Plex server?

**Comment by YaBoiDan** [comment] 2024-08-27 20:44
Two Plex servers, one serves Music, the other serves Films, TV, and Other Video. Removing the Music server (After also removing the custom show) allows me to go back in and create more shows. Definitely looks like an issue jumping between the two. Perhaps it's trying to jump between server 1 to server 2 but keep the library the same, as neither shares a library, it causes issues?

**Comment by chrisbenincasa** [comment] 2024-08-27 20:46
Gotcha, thanks for clarifying. I'll see if I can get a solid reproduction on my end.

**Comment by YaBoiDan** [comment] 2024-08-27 20:57
Great, cheers, let me know if I can do anything to help! 
Love the app BTW!

**Comment by chrisbenincasa** [comment] 2024-08-27 21:20
Thanks!

I setup a 2nd PMS locally. I see some weirdness when switching between the 2 servers (blank library select dropdown) but I haven't been able to reproduce the error yet. I'll keep trying!

**Comment by chrisbenincasa** [comment] 2024-08-27 21:22
NVM - I just got it!

**Comment by chrisbenincasa** [comment] 2024-08-27 21:23
Pasting the non-minified/obfuscated stack here:

```
TypeError: Cannot read properties of undefined (reading 'guid')
    at uniqueId (http://localhost:5173/web/src/store/programmingSelector/actions.ts?t=1724791098129:17:21)
    at http://localhost:5173/web/src/store/programmingSelector/actions.ts?t=1724791098129:30:18
    at Array.reduce (<anonymous>)
    at http://localhost:5173/web/src/store/programmingSelector/actions.ts?t=1724791098129:28:30
    at http://localhost:5173/web/node_modules/.vite/deps/zustand_middleware_immer.js?v=ef13d432:516:56
    at Immer2.produce (http://localhost:5173/web/node_modules/.vite/deps/zustand_middleware_immer.js?v=ef13d432:529:20)
    at curriedProduce (http://localhost:5173/web/node_modules/.vite/deps/zustand_middleware_immer.js?v=ef13d432:516:23)
    at setState (http://localhost:5173/web/node_modules/.vite/deps/zustand.js?v=ef13d432:16:55)
    at store.setState (http://localhost:5173/web/node_modules/.vite/deps/zustand_middleware_immer.js?v=ef13d432:677:12)
    at api.setState (http://localhost:5173/web/node_modules/.vite/deps/zustand_middleware.js?v=ef13d432:58:15)
```

**Comment by chrisbenincasa** [comment] 2024-08-29 18:04
This is a finicky one, i can't seem to get it to reproduce consistently. Still trying to break it down

**Comment by chrisbenincasa** [comment] 2024-08-29 19:07
So i have something that at least prevent the error above in https://github.com/chrisbenincasa/tunarr/pull/733 and also improve the experience of switching libraries. I can't get a consistent repro, but hopefully this 'stops the bleeding'

**Comment by chrisbenincasa** [comment] 2024-08-29 19:10
Will be included in the 0.9.0 release

**Comment by chrisbenincasa** [comment] 2024-08-31 16:34
Going to close this out since I think the latest changes should fix this, but please let me know if you are still having trouble.

**Closed** 2024-08-31 16:34 UTC
Labels: bug

**Comment by YaBoiDan** [comment] 2024-08-31 22:58
Hey, that seemed to work after updating to 0.9.0, thank you! :)

**Comment by chrisbenincasa** [comment] 2024-08-31 23:06
Awesome! You’re welcome.
