### ISSUE TITLE
[Bug]: Add program to channel perf regression after external ID introduction

### ISSUE THREAD

**Issue by josway** [chrisbenincasa/tunarr#543] opened 2024-06-18 15:49 UTC
### What happened?

Getting an Error 504 when saving channels with lots of programs. Some times it does end up saving even though it throws the error and some times it does not. Not sure what the amount of programs causes the issue but working on one now that is 376 programs and is about 50/50 on whether it saves or errors out. It does throw the 504 error each time though. 

### Version

0.1.0

### Relevant log output

```shell
Not seeing any relevant logs or errors.
```

**Comment by josway** [comment] 2024-06-18 16:22
Let me know if this is helpful.

[Console.txt](https://github.com/user-attachments/files/15889636/Console.txt)

**Comment by chrisbenincasa** [comment] 2024-06-18 16:26
Hmmm, nothing sticks out there. Was hoping for some more specific error details. 504 is actually pretty interesting... I think the parsing issues actually would manifest as 500s. 504 replies that the server is just taking too long, not something I've seen before. Let me see if I can reproduce on my build with a lot of programs.

**Comment by chrisbenincasa** [comment] 2024-06-18 16:28
If you watch your browser network tab while it's saving - how long is that POST request taking? 

I just executed a channel update for about 750 channels and it took 8 seconds on the server.

**Comment by josway** [comment] 2024-06-18 16:39
I'll have to check this later. After testing out the backups again, I can't seem to keep the container running. See #544.

**Comment by josway** [comment] 2024-06-18 19:04
Wow! Just ran this under my fresh install and it was 1.7 mins on that event. It did end up saving the programs but was only about half of the number you processed in seconds...hmmm.

**Comment by chrisbenincasa** [comment] 2024-06-18 19:45
Wooof yea, that is quite slow. I haven't experienced anything even close to that on my local machine, which is pretty modest. What type of hardware are you running Tunarr on, out of curiosity?

**Comment by chrisbenincasa** [comment] 2024-06-18 19:50
I'm going to see if there is some work we can push to the background on this path. Usually the DB queries / inserts are very fast. This path does 3 things:

1. Use the Plex metadata sent from the frontend to create or update programs in the DB
2. Use the Plex metadata sent from the frontend to create or update  program "external ids" in the DB
3. For tv shows / music tracks, we will follow parent/grandparent IDs by querying Plex to create the hierarchies in our DB (albums/artists + seasons/shows). This could potentially be slow.

One thing I can do is add some performance debug logging on this path and have you try this and post the results.

**Comment by josway** [comment] 2024-06-18 19:59
Yeah it's not a hardware issue. Running on Dual Xeon's with 64GB of RAM. 

Generally things have been very quick to query. Could it possibly be the path to Plex? I am currently using an external IP address Plex URL rather than a local one. This worked better previously with DizqueTV. I could play around with that on my end if it could possibly be.

**Comment by chrisbenincasa** [comment] 2024-06-18 20:17
Ah yep, that's definitely not the problem. It could very well be a network issue ... if you have the http log level enabled you should see latency measurements for all outgoing plex queries. There will be quite a few of them when upserting programs.

I just created a fresh database to ensure that we were doing all inserts and not skipping any work. Some preliminary results:

```
@tunarr/server:dev: 2024-06-18T20:14:31.555Z [debug]: findAndUpdateProgramRelations took 2656.43 (success)
@tunarr/server:dev: 2024-06-18T20:14:31.660Z [debug]: upsertContentPrograms to 17285.341 millis. 771 upsertedPrograms
```

**Comment by chrisbenincasa** [comment] 2024-06-18 20:26
Some more measurements on an even larger set:

```
@tunarr/server:dev: 2024-06-18T20:24:18.665Z [debug]: Upserting 1907 programs                                                 
@tunarr/server:dev: 2024-06-18T20:24:20.842Z [debug]: upsertProgramsDB took 2177.057 (success)                                @tunarr/server:dev: 2024-06-18T20:24:53.915Z [debug]: upsertProgramExternalIds took 33058.136 (success) 
@tunarr/server:dev: 2024-06-18T20:25:01.477Z [debug]: findAndUpdateProgramRelations took 7560.623 (success)
@tunarr/server:dev: 2024-06-18T20:25:01.712Z [debug]: upsertContentPrograms to 43786.908 millis. 1907 upsertedPrograms
@tunarr/server:dev: 2024-06-18T20:25:02.216Z [debug] <dao/channelDb.ts>: createNewLineup took 44290.791 (success)
@tunarr/server:dev: 2024-06-18T20:25:02.787Z [debug] <dao/channelDb.ts>: updateChannel took 571.503 (success)
@tunarr/server:dev: 2024-06-18T20:25:02.852Z [info] <tasks/Task.ts>: Task ReconcileProgramDurationsTask ran in 2.69 ms {"task":"ReconcileProgramDurationsTask"}
@tunarr/server:dev: 2024-06-18T20:25:02.852Z [debug] <dao/channelDb.ts>: saveLineup took 64.576 (success)
```
 Note that some of these measurements contain the others... upserting external IDs is clearly a problem here.

**Comment by josway** [comment] 2024-06-19 15:21
After the browser timeout, If I just wait long enough, 3-5 mins, the upserting does complete and the channel programming is saved. Not seeing times anywhere close to yours but let me know if I can provide anything further to help. Will be curious to see if these improvements on your end, help on mine.

**Comment by chrisbenincasa** [comment] 2024-06-19 15:25
Definitely. I probably won't have a chance today but I'd be curious to get a build out with the perf trace logs and have you run the insert to see if the slow areas are the same. I have an inkling they are. 

I have two things in progress:
- Instead of serially writing all of the external ids, which we have to do because of a current limitation in the ORM we're using with upserts and conditional indexes, we just do a read-before-write and calculate the differences in memory. Not ideal but I think it's ok in this situation
- Moving program grouping (hierarchy) building to a background task triggered on upsert. This is something I've been meaning to do anyway

In theory the biggest wins should be with the first change

**Comment by chrisbenincasa** [comment] 2024-06-21 14:21
Sorry for the delay here. I have some improvements locally but I've fallen down a bit of a rabbit hole with some other perf issues I've noticed with super large channels. 

At this point the change is quite large, so I think I may make it the first change to go into the dev branch (the new source of the edge tag soon)

**Comment by chrisbenincasa** [comment] 2024-06-22 12:00
Ok, I have a _ton_ of changes in #552. I'll merge it into the dev branch once it's built and then kick off a build. I've kept the timing code in there at debug log level, so if it's still unbearably slow you can post your measurements here.

**Comment by josway** [comment] 2024-06-25 15:49
I am unable to manually pull the dev branch on Unraid. Getting an image not found error. Should @nwithan8 update the template to include the dev branch as well? Not sure if there is another step in between or if it's on my end. Happy to keep testing out those changes once I can grab that image.

**Comment by josway** [comment] 2024-06-25 18:46
Ah! My bad. I thought you were referring to a separate new dev build above. I’ll run some test channels on the newest edge update then.

**Comment by josway** [comment] 2024-06-26 15:57
Definitely seeing big improvements but still nowhere near your times. Just built a ~700 program channel in 48 sec and no timeout. Improvement but still not sure what's up on my end. Hopefully someone else can give you some more details that can help continue to improve things. At this point it's useable for me. Will keep playing around with things. 

2024-06-26T15:53:27.035Z [debug]: loadLineup took 0.042 (success)
2024-06-26T15:53:27.036Z [debug]: select channel took 0.195 (success)
2024-06-26T15:53:27.639Z [debug]: gather programs took 602.192 (success)
2024-06-26T15:53:27.724Z [debug]: program convert took 5.234 (success)
2024-06-26T15:53:27.800Z [debug]: build condensed lineup took 75.664 (success)
2024-06-26T15:54:18.520Z [debug]: loadLineup took 0.026 (success)
2024-06-26T15:54:18.521Z [debug]: select channel took 0.188 (success)
2024-06-26T15:54:19.215Z [debug]: gather programs took 692.92 (success)
2024-06-26T15:54:19.302Z [debug]: program convert took 4.941 (success)
2024-06-26T15:54:19.371Z [debug]: build condensed lineup took 68.232 (success)
2024-06-26T15:54:21.063Z [debug]: loadLineup took 0.018 (success)
2024-06-26T15:54:21.063Z [debug]: select channel took 0.144 (success)
2024-06-26T15:54:21.611Z [debug]: gather programs took 546.957 (success)
2024-06-26T15:54:21.689Z [debug]: program convert took 8.661 (success)
2024-06-26T15:54:21.760Z [debug]: build condensed lineup took 69.509 (success)

**Comment by chrisbenincasa** [comment] 2024-06-26 17:49
Happy to hear there is improvement, but still wanna figure out what is going on! I noticed that times on my workstation (NVMe drive) were _much_ speedier than my laptop (SSD), interestingly. Naturally I imagine sqlite would be faster on a faster drive... 

On another branch I'm messing around with ditching our ORM for some queries, since there is a non-trivial overhead when select tons of entities. Since the query builder ditches a lot of the niceties of the ORM (entity managerment, etc) we'd naturally see a significant improvement in some areas. If I have success there, I may also work to substitute this "direct" access on the more critical paths that tend to deal with a ton of data (lineups). 

Those timings look like they are for selecting the lineup. Let me know if you can grab timings for creating a channel. The create path should have timings like "upsertProgramsDB" and "upsert external ids"

**Comment by josway** [comment] 2024-06-26 18:29
Brand new channel with 621 programs

2024-06-26T18:24:31.341Z [debug]: Push event: Started building tv-guide at = 2024-06-26T13:24:31-05:00
2024-06-26T18:24:50.043Z [debug]: loadLineup took 0.028 (success)
2024-06-26T18:24:50.044Z [debug]: select channel took 0.162 (success)
2024-06-26T18:24:50.045Z [debug]: gather programs took 0.013 (success)
2024-06-26T18:24:50.045Z [debug]: program convert took 0.068 (success)
2024-06-26T18:24:50.049Z [debug]: build condensed lineup took 3.706 (success)
2024-06-26T18:24:50.050Z [debug]: Generated and wrote xmltv file in 69.905ms
2024-06-26T18:24:50.051Z [debug]: Push event: XMLTV updated at server time = 2024-06-26T18:24:50.051Z
2024-06-26T18:24:50.052Z [debug]: Built TV Guide for a day in 164.062 millis
2024-06-26T18:24:50.052Z [info]: XMLTV Updated at 6/26/2024, 1:24:50 PM {"task":"update-xmltv"}
2024-06-26T18:24:50.060Z [debug]: Task UpdateXmlTvTask ran in 18720.82 ms {"task":"update-xmltv"}
2024-06-26T18:26:23.098Z [debug]: loadLineup took 0.034 (success)
2024-06-26T18:26:23.099Z [debug]: select channel took 0.171 (success)
2024-06-26T18:26:23.099Z [debug]: gather programs took 0.013 (success)
2024-06-26T18:26:23.099Z [debug]: program convert took 0.011 (success)
2024-06-26T18:26:23.103Z [debug]: build condensed lineup took 3.278 (success)
2024-06-26T18:27:02.291Z [debug]: Upserting 621 programs
2024-06-26T18:27:05.166Z [debug]: upsertProgramsDB took 2874.152 (success)
2024-06-26T18:27:17.219Z [debug]: upsert external ids took 12042.536 (success)
2024-06-26T18:27:17.373Z [debug]: Took 13.05523799918592 ms to schedule tasks
2024-06-26T18:27:17.374Z [debug]: upsertContentPrograms to 15241.823 millis. 621 upsertedPrograms
2024-06-26T18:27:17.428Z [debug]: createNewLineup took 15296.722 (success)
2024-06-26T18:27:17.976Z [debug]: updateChannel took 547.411 (success)
2024-06-26T18:27:18.028Z [debug]: saveLineup took 50.994 (success)
2024-06-26T18:27:18.029Z [debug]: loadLineup took 0.03 (success)
2024-06-26T18:27:18.030Z [debug]: select channel took 0.25 (success)
2024-06-26T18:27:18.579Z [debug]: gather programs took 547.582 (success)
2024-06-26T18:27:18.640Z [debug]: program convert took 3.721 (success)
2024-06-26T18:27:18.688Z [debug]: build condensed lineup took 47.866 (success)
2024-06-26T18:27:18.690Z [debug]: build fresh lineup took 660.135 (success)
2024-06-26T18:27:30.997Z [debug]: Task ReconcileProgramDurationsTask ran in 12269.68 ms {"task":"ReconcileProgramDurationsTask"}
2024-06-26T18:27:31.001Z [debug]: Push event: Started building tv-guide at = 2024-06-26T13:27:31-05:00
2024-06-26T18:27:56.252Z [debug]: loadLineup took 0.019 (success)
2024-06-26T18:27:56.253Z [debug]: select channel took 0.151 (success)
2024-06-26T18:27:56.680Z [debug]: gather programs took 426.245 (success)
2024-06-26T18:27:59.758Z [debug]: program convert took 3.894 (success)
2024-06-26T18:28:01.435Z [debug]: build condensed lineup took 1676.025 (success)
2024-06-26T18:28:02.692Z [debug]: Generated and wrote xmltv file in 58.995ms
2024-06-26T18:28:02.693Z [debug]: Push event: XMLTV updated at server time = 2024-06-26T18:28:02.693Z
2024-06-26T18:28:02.694Z [debug]: Built TV Guide for a day in 6991.173 millis
2024-06-26T18:28:02.695Z [info]: XMLTV Updated at 6/26/2024, 1:28:02 PM {"task":"update-xmltv"}
2024-06-26T18:28:02.702Z [debug]: Task UpdateXmlTvTask ran in 44673.19 ms {"task":"update-xmltv"}

**Comment by josway** [comment] 2024-06-26 18:31
Upon creating a second new channel I ran into this error. This was just on channel creation. 

2024-06-26T18:29:21.618Z [debug]: select channel took 0.159 (success)
2024-06-26T18:29:22.088Z [debug]: gather programs took 468.761 (success)
2024-06-26T18:29:22.158Z [debug]: program convert took 4.887 (success)
2024-06-26T18:29:22.219Z [debug]: build condensed lineup took 60.147 (success)
2024-06-26T18:29:47.293Z [debug]: Push event: Started building tv-guide at = 2024-06-26T13:29:47-05:00
2024-06-26T18:30:09.668Z [debug]: Task CleanupSessionsTask ran in 0.2 ms
2024-06-26T18:30:09.672Z [error]: Plex request error: socket hang up 
    err: {
      "message": "socket hang up: socket hang up",
      "name": "Error",
      "stack":
          Error: socket hang up
              at AxiosError.from (file:///tunarr/server/build/bundle.js:241511:14)
              at RedirectableRequest.handleRequestError (file:///tunarr/server/build/bundle.js:243258:34)
              at RedirectableRequest.emit (node:events:519:28)
              at eventHandlers.<computed> (file:///tunarr/server/build/bundle.js:121942:28)
              at ClientRequest.emit (node:events:519:28)
              at TLSSocket.socketOnEnd (node:_http_client:524:9)
              at TLSSocket.emit (node:events:531:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
          caused by: Error: socket hang up
              at TLSSocket.socketOnEnd (node:_http_client:524:23)
              at TLSSocket.emit (node:events:531:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json",
          "X-Plex-Device": "Tunarr",
          "X-Plex-Device-Name": "Tunarr",
          "X-Plex-Product": "Tunarr",
          "X-Plex-Version": "0.1",
          "X-Plex-Client-Identifier": "p86cy1w47clco3ro8t92nfy1",
          "X-Plex-Platform": "Chrome",
          "X-Plex-Platform-Version": "80.0",
          "X-Plex-Token": "xriinDdAtxsjfmutGycy",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "https://67-4-135-239.f7b9c382cdb54276a8d140eef0f50f4a.plex.direct:32400",
        "method": "get",
        "url": "/library/metadata/16994",
        "metadata": {
          "startTime": 1719426609659
        }
      },
      "code": "ECONNRESET",
      "status": null
    }
2024-06-26T18:30:09.673Z [error]: Error querying Plex for item 16994
2024-06-26T18:30:09.683Z [error]: Plex request error: socket hang up 
    err: {
      "message": "socket hang up: socket hang up",
      "name": "Error",
      "stack":
          Error: socket hang up
              at AxiosError.from (file:///tunarr/server/build/bundle.js:241511:14)
              at RedirectableRequest.handleRequestError (file:///tunarr/server/build/bundle.js:243258:34)
              at RedirectableRequest.emit (node:events:519:28)
              at eventHandlers.<computed> (file:///tunarr/server/build/bundle.js:121942:28)
              at ClientRequest.emit (node:events:519:28)
              at TLSSocket.socketOnEnd (node:_http_client:524:9)
              at TLSSocket.emit (node:events:531:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
          caused by: Error: socket hang up
              at TLSSocket.socketOnEnd (node:_http_client:524:23)
              at TLSSocket.emit (node:events:531:35)
              at endReadableNT (node:internal/streams/readable:1696:12)
              at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
      "config": {
        "transitional": {
          "silentJSONParsing": true,
          "forcedJSONParsing": true,
          "clarifyTimeoutError": false
        },
        "adapter": [
          "xhr",
          "http"
        ],
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
          "Accept": "application/json",
          "X-Plex-Device": "Tunarr",
          "X-Plex-Device-Name": "Tunarr",
          "X-Plex-Product": "Tunarr",
          "X-Plex-Version": "0.1",
          "X-Plex-Client-Identifier": "p86cy1w47clco3ro8t92nfy1",
          "X-Plex-Platform": "Chrome",
          "X-Plex-Platform-Version": "80.0",
          "X-Plex-Token": "xriinDdAtxsjfmutGycy",
          "User-Agent": "axios/1.6.0",
          "Accept-Encoding": "gzip, compress, deflate, br"
        },
        "baseURL": "https://67-4-135-239.f7b9c382cdb54276a8d140eef0f50f4a.plex.direct:32400",
        "method": "get",
        "url": "/library/metadata/16991",
        "metadata": {
          "startTime": 1719426609657
        }
      },
      "code": "ECONNRESET",
      "status": null
    }
2024-06-26T18:30:09.684Z [error]: Error querying Plex for item 16991
2024-06-26T18:30:09.890Z [debug]: loadLineup took 0.018 (success)
2024-06-26T18:30:09.891Z [debug]: select channel took 0.151 (success)
2024-06-26T18:30:09.891Z [debug]: gather programs took 0.011 (success)
2024-06-26T18:30:09.892Z [debug]: program convert took 0.012 (success)
2024-06-26T18:30:09.897Z [debug]: build condensed lineup took 5.729 (success)
2024-06-26T18:30:10.274Z [debug]: Generated and wrote xmltv file in 59.844ms
2024-06-26T18:30:10.274Z [debug]: Push event: XMLTV updated at server time = 2024-06-26T18:30:10.274Z
2024-06-26T18:30:10.275Z [debug]: Built TV Guide for a day in 639.81 millis
2024-06-26T18:30:10.276Z [info]: XMLTV Updated at 6/26/2024, 1:30:10 PM {"task":"update-xmltv"}
2024-06-26T18:30:10.283Z [debug]: Task UpdateXmlTvTask ran in 22993.02 ms {"task":"update-xmltv"}

**Comment by josway** [comment] 2024-06-26 18:35
And timings on finishing the second channel with 3x the programs.

2024-06-26T18:32:49.380Z [debug]: loadLineup took 0.033 (success)
2024-06-26T18:32:49.381Z [debug]: select channel took 0.207 (success)
2024-06-26T18:32:49.381Z [debug]: gather programs took 0.013 (success)
2024-06-26T18:32:49.381Z [debug]: program convert took 0.008 (success)
2024-06-26T18:32:49.385Z [debug]: build condensed lineup took 3.427 (success)
2024-06-26T18:33:13.069Z [debug]: loadLineup took 0.049 (success)
2024-06-26T18:33:13.070Z [debug]: select channel took 0.235 (success)
2024-06-26T18:33:13.071Z [debug]: gather programs took 0.018 (success)
2024-06-26T18:33:13.071Z [debug]: program convert took 0.012 (success)
2024-06-26T18:33:13.075Z [debug]: build condensed lineup took 3.598 (success)
2024-06-26T18:33:25.425Z [debug]: Upserting 1763 programs
2024-06-26T18:33:32.584Z [debug]: upsertProgramsDB took 7159.396 (success)
2024-06-26T18:34:04.811Z [debug]: upsert external ids took 32215.493 (success)
2024-06-26T18:34:05.038Z [debug]: Took 35.61136299930513 ms to schedule tasks
2024-06-26T18:34:05.039Z [debug]: upsertContentPrograms to 42726.981 millis. 1763 upsertedPrograms
2024-06-26T18:34:05.734Z [debug]: createNewLineup took 43421.652 (success)
2024-06-26T18:34:07.011Z [debug]: updateChannel took 1276.41 (success)
2024-06-26T18:34:07.094Z [debug]: saveLineup took 82.336 (success)
2024-06-26T18:34:07.094Z [debug]: loadLineup took 0.028 (success)
2024-06-26T18:34:07.095Z [debug]: select channel took 0.237 (success)
2024-06-26T18:34:08.306Z [debug]: gather programs took 1208.097 (success)
2024-06-26T18:34:13.648Z [debug]: program convert took 14.311 (success)
2024-06-26T18:34:14.335Z [debug]: build condensed lineup took 686.74 (success)
2024-06-26T18:34:14.337Z [debug]: build fresh lineup took 7242.226 (success)
2024-06-26T18:34:24.699Z [debug]: Task ReconcileProgramDurationsTask ran in 10247.05 ms {"task":"ReconcileProgramDurationsTask"}
2024-06-26T18:34:24.700Z [debug]: Push event: Started building tv-guide at = 2024-06-26T13:34:24-05:00
2024-06-26T18:34:53.015Z [debug]: loadLineup took 0.022 (success)
2024-06-26T18:34:53.016Z [debug]: select channel took 0.157 (success)
2024-06-26T18:34:54.270Z [debug]: gather programs took 1252.81 (success)
2024-06-26T18:34:55.010Z [debug]: program convert took 10.344 (success)
2024-06-26T18:34:55.741Z [debug]: build condensed lineup took 730.039 (success)
2024-06-26T18:34:56.865Z [debug]: Generated and wrote xmltv file in 53.83ms
2024-06-26T18:34:56.866Z [debug]: Push event: XMLTV updated at server time = 2024-06-26T18:34:56.866Z
2024-06-26T18:34:56.867Z [debug]: Built TV Guide for a day in 5006.636 millis
2024-06-26T18:34:56.867Z [info]: XMLTV Updated at 6/26/2024, 1:34:56 PM {"task":"update-xmltv"}
2024-06-26T18:34:56.874Z [debug]: Task UpdateXmlTvTask ran in 49779.95 ms {"task":"update-xmltv"}

**Comment by chrisbenincasa** [comment] 2024-06-26 18:42
I've seen the socket hangups from time to time - still working those out. A lot of times they happen in background tasks that fire off when creating channels, especially large ones. Did the creation actually error our there? 

As for the timings... it's slow where I expected, but still way slower than I anticipated. The external IDs insertion is still really bad. For the synchronous portion there we are doing batches of 100 inserts (split between two different types of inserts) over 2x the number of programs being inserted (2 IDs per program). So a 2k channel program will generate 4k IDs (one plex rating key and one plex GUID), and thus 80 upserts (4k / 50). 

For comparison, I have some timings on my local dev server when saving about 2k items:

```
@tunarr/server:dev: 2024-06-26T18:40:02.657Z [debug] <dao/channelDb.ts>: loadLineup took 0.066 (success)
@tunarr/server:dev: 2024-06-26T18:40:02.658Z [debug] <dao/channelDb.ts>: select channel took 0.122 (success)                  
@tunarr/server:dev: 2024-06-26T18:40:02.658Z [debug] <dao/channelDb.ts>: gather programs took 0.009 (success)
@tunarr/server:dev: 2024-06-26T18:40:02.658Z [debug] <dao/channelDb.ts>: program convert took 0.003 (success)                 
@tunarr/server:dev: 2024-06-26T18:40:02.659Z [debug] <dao/channelDb.ts>: build condensed lineup took 1.147 (success)
@tunarr/server:dev: 2024-06-26T18:40:08.450Z [debug]: Upserting 1903 programs                                                 
@tunarr/server:dev: 2024-06-26T18:40:09.020Z [debug]: upsertProgramsDB took 569.075 (success)           
@tunarr/server:dev: 2024-06-26T18:40:09.980Z [debug]: upsert external ids took 929.312 (success)                              
@tunarr/server:dev: 2024-06-26T18:40:10.039Z [debug]: Took 23.4046129998751 ms to schedule tasks       
@tunarr/server:dev: 2024-06-26T18:40:10.039Z [debug]: upsertContentPrograms to 2804.298 millis. 1903 upsertedPrograms         
@tunarr/server:dev: 2024-06-26T18:40:10.553Z [debug] <dao/channelDb.ts>: createNewLineup took 3317.72 (success)
@tunarr/server:dev: 2024-06-26T18:40:11.018Z [debug] <dao/channelDb.ts>: updateChannel took 465.316 (success)                 
@tunarr/server:dev: 2024-06-26T18:40:11.101Z [debug] <dao/channelDb.ts>: saveLineup took 82.756 (success)
@tunarr/server:dev: 2024-06-26T18:40:11.102Z [debug] <dao/channelDb.ts>: loadLineup took 0.064 (success)
@tunarr/server:dev: 2024-06-26T18:40:11.102Z [debug] <dao/channelDb.ts>: select channel took 0.188 (success)
@tunarr/server:dev: 2024-06-26T18:40:11.752Z [debug] <dao/channelDb.ts>: gather programs took 648.971 (success)
@tunarr/server:dev: 2024-06-26T18:40:13.032Z [debug] <dao/channelDb.ts>: program convert took 5.921 (success)
@tunarr/server:dev: 2024-06-26T18:40:13.540Z [debug] <dao/channelDb.ts>: build condensed lineup took 507.844 (success)
@tunarr/server:dev: 2024-06-26T18:40:13.542Z [debug]: build fresh lineup took 2440.485 (success)
```

Pretty wild that my external ID upsert takes less than a second here. I will keep digging around.

I'll also try and reproduce the socket hangup... I haven't seen that on my local machine since I merged in the perf changes. Is your Plex server remote by any chance?

**Comment by josway** [comment] 2024-06-26 18:54
Plex and Tunarr are on the same machine. 
Tunarr is connected to Plex via an external IP. This was a mirror of my dizque setup. Could look at changing this but think you previously said it shouldn't matter. 
I am accessing Tunarr in my browser via a reverse proxy with NPM (nginxproxymanager).

**Comment by chrisbenincasa** [comment] 2024-06-26 18:55
Yea was just asking in reference to the socket hangups. Trying to figure out a common cause for those. That shouldn't have a bearing on the performance (maybe we should start a separate thread for the socket hangup issue)

**Comment by chrisbenincasa** [comment] 2024-06-26 19:00
I'm able to reproduce the slowness for inserting massive amounts of programs on my test deploy on my own server (spinning rust). Going to try a few things and see if I can get this to be a bit quicker

**Comment by chrisbenincasa** [comment] 2024-06-26 19:02
Oh wait - this is my bad - I think i'm running an older version, haha. Let me do a fresh deploy.

**Comment by chrisbenincasa** [comment] 2024-06-26 19:14
OK - some timings from my server. For context this is Tunarr running in Docker, nested in an LXC. Storage is old disks...

```
2024-06-26T19:12:37.658Z [debug]: Upserting 2211 programs
2024-06-26T19:12:43.552Z [debug]: upsertProgramsDB took 5893.365 (success)
2024-06-26T19:12:53.556Z [debug]: upsert external ids took 9815.377 (success)
2024-06-26T19:12:54.340Z [debug]: Took 30.310330000007525 ms to schedule tasks
2024-06-26T19:12:54.341Z [debug]: upsertContentPrograms to 18875.183 millis. 2211 upsertedPrograms                            
2024-06-26T19:12:55.981Z [debug]: createNewLineup took 20516.025 (success)
2024-06-26T19:12:57.519Z [debug]: updateChannel took 1537.802 (success)
```

So I see some slowness here too. Going to test out some of my theories.

I also got a single errant socket hang up while doing the save. Will look into that too

**Comment by chrisbenincasa** [comment] 2024-06-27 20:16
Have some more improvements here: https://github.com/chrisbenincasa/tunarr/pull/593

**Comment by josway** [comment] 2024-06-27 20:34
Seeing significant improvements...including the warnings as those are new on my end. 

2024-06-27T20:28:22.109Z [debug]: loadLineup took 0.127 (success)
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
2024-06-27T20:28:22.112Z [debug]: select channel took 2.065 (success)
2024-06-27T20:28:22.118Z [debug]: direct took 5.043 (success)
2024-06-27T20:28:22.184Z [debug]: eids took 65.382 (success)
2024-06-27T20:28:22.185Z [debug]: program convert took 0.176 (success)
2024-06-27T20:28:22.190Z [debug]: build condensed lineup took 5.274 (success)
2024-06-27T20:29:34.031Z [info]: Remove event channel.
2024-06-27T20:29:35.963Z [debug]: loadLineup took 0.09 (success)
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
2024-06-27T20:29:35.965Z [debug]: select channel took 1.521 (success)
2024-06-27T20:29:35.968Z [debug]: direct took 2.107 (success)
2024-06-27T20:29:35.977Z [debug]: eids took 9.046 (success)
2024-06-27T20:29:35.978Z [debug]: program convert took 0.005 (success)
2024-06-27T20:29:35.980Z [debug]: build condensed lineup took 2.477 (success)
2024-06-27T20:29:49.981Z [debug]: Upserting 2407 programs
2024-06-27T20:29:51.143Z [debug]: upsertProgramsDB took 1161.421 (success)
2024-06-27T20:30:03.372Z [debug]: upsert external ids took 12209.293 (success)
2024-06-27T20:30:03.515Z [debug]: Took 26.294632000033744 ms to schedule tasks
2024-06-27T20:30:03.516Z [debug]: upsertContentPrograms to 15028.99 millis. 2407 upsertedPrograms
2024-06-27T20:30:03.528Z [debug]: createNewLineup took 15041.815 (success)
2024-06-27T20:30:05.451Z [debug]: updateChannel took 1922.2 (success)
2024-06-27T20:30:05.568Z [debug]: Running task CleanupSessionsTask
2024-06-27T20:30:05.569Z [debug]: Task CleanupSessionsTask ran in 0.28 ms
2024-06-27T20:30:05.590Z [debug]: saveLineup took 138.689 (success)
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
(node:1) Warning: No such label 'req' for console.timeLog()
2024-06-27T20:30:05.591Z [debug]: Running task UpdateXmlTvTask {"task":"update-xmltv"}
2024-06-27T20:30:05.592Z [debug]: loadLineup took 0.1 (success)
2024-06-27T20:30:05.593Z [debug]: select channel took 0.318 (success)
2024-06-27T20:30:05.721Z [debug]: direct took 127.485 (success)
2024-06-27T20:30:05.912Z [debug]: eids took 190.352 (success)
2024-06-27T20:30:05.953Z [debug]: program convert took 29.897 (success)
2024-06-27T20:30:05.962Z [debug]: build condensed lineup took 7.867 (success)
2024-06-27T20:30:05.968Z [debug]: build fresh lineup took 376.408 (success)

**Comment by chrisbenincasa** [comment] 2024-06-27 20:47
Ahhhh I think I may have left those accidentally. I will remove them
shortly but they shouldn’t cause any harm.

**Comment by chrisbenincasa** [comment] 2024-06-27 22:36
Logs removed in #594

I think I will close this one out now and open some more targeted issues around performance

**Closed** 2024-07-07 11:39 UTC
Labels: bug, performance
